openapi: 3.0.1
info:
  title: monster-flesh-golem
  x-cortex-tag: monster-flesh-golem
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: aberration
    challenge_rating: 1
    legendary: false
    armor_class: 14
    hit_points: 61
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-flesh-golem
      alias: github-token-test
